### ISSUE TITLE
Development Tracking of the Ignition ModelPhotoShot plugin

### ISSUE THREAD

**Issue by marcoag** [marcoag/ign-modelphotoshoot#1]
This is the current progress on the different steps needed to achieve a functional plugin:

- [x] Load model into ign-gazebo (done through the sdf config, couldn't find a way to receive command line params in a plugin)
- [x] Create camera
- [x] Create lights
- [ ] Change background color (not working yet)
- [x] Render and take picture with camera
- [x] Center model in picture
- [x] Add different picture positions
- [ ] Make model move in random position
- [x] Add save-to-file option for the poses
- [ ] Shutdown server (it seems that this feature still not available: https://github.com/ignitionrobotics/ign-gazebo/issues/1237)

Currently working on: Testing current results against drake.

**Comment by marcoag** [comment]
Work towards https://github.com/EricCousineau-TRI/repro/pull/73.

FYI @EricCousineau-TRI.

**Comment by luca-della-vedova** [comment]
Thanks for picking this up, this would be super useful! A few scattered thoughts

> 
>     * [ ]  Change background color (not working yet)

Looks like there should be [support](http://sdformat.org/spec?ver=1.9&elem=scene#scene_background) in `sdformat` for setting a scene's background color but to be honest I've never used it so I don't know if it works, I have considered in the past enclosing the whole model in a big colored sphere but that doesn't sound too clean :sweat_smile: 

>     * [ ]  Make model move in random position

I was wondering what is the need of this? From what I understand for the sake of taking snapshots it is preferable to have a few fixed poses (i.e. top, perspective, side, front) and the usual approach is to move the camera around instead?

>     * [ ]  Shutdown server (it seems that this feature still not available: [/server_control stop does nothing ignitionrobotics/ign-gazebo#1237](https://github.com/ignitionrobotics/ign-gazebo/issues/1237))

If you plan to run this plugin through `ign gazebo`, something that could help is the `--iterations` argument where you can set the number of iterations to run before closing the software cleanly, so for example if you wanted to run headless for 5 seconds and you were using the default 1ms time step you could run:

```
ign gazebo model_photo_shoot.sdf -r -s --iterations 5000
```

**Comment by marcoag** [comment]
Thanks for all the info, it's very helpful! 

> Looks like there should be [support](http://sdformat.org/spec?ver=1.9&elem=scene#scene_background) in `sdformat` for setting a scene's background color but to be honest I've never used it so I don't know if it works, I have considered in the past enclosing the whole model in a big colored sphere but that doesn't sound too clean :sweat_smile:

I tried the sdformat background option and it didn't work. I also tested using [SetBackgroundColor](https://ignitionrobotics.org/api/rendering/6.1/classignition_1_1rendering_1_1Scene.html#a3a202de0928fc8a2abe9f58f0c92e93a) on the scene instance without much luck, maybe I'm missing something, will do more research on this...

> I was wondering what is the need of this? From what I understand for the sake of taking snapshots it is preferable to have a few fixed poses (i.e. top, perspective, side, front) and the usual approach is to move the camera around instead?

This is just a requirement we have, since we will compare the results of this plugin with `drake`. Maybe a more generic option where the position is not only random but can be set to something specific somehow is a better option but I'm not sure how that could be done... random is enough for us anyway.

> If you plan to run this plugin through `ign gazebo`, something that could help is the `--iterations` argument where you can set the number of iterations to run before closing the software cleanly, so for example if you wanted to run headless for 5 seconds and you were using the default 1ms time step you could run:
> 
> ```
> ign gazebo model_photo_shoot.sdf -r -s --iterations 5000
> ```

This great! That should probably work for now. Thanks!

**Comment by EricCousineau-TRI** [comment]
Just for tracking - is this a fair "downstream motivation" issue?
https://github.com/RobotLocomotion/drake/issues/15024

Also, is it possible to mention this plugin, and perhaps provide a comparison?
https://community.gazebosim.org/t/gsoc-2021-machine-learning-extension-to-ignition-gazebo/1070

**Comment by luca-della-vedova** [comment]
> This is just a requirement we have, since we will compare the results of this plugin with `drake`. Maybe a more generic option where the position is not only random but can be set to something specific somehow is a better option but I'm not sure how that could be done... random is enough for us anyway.

The [set_pose](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo6/src/systems/user_commands/UserCommands.cc#L595-L597) service should work for the purpose.
If I remember correctly you can use either the `Entity` or the model's `name` to tell the system which model you want to set the pose of, example usage is [here](https://github.com/ignitionrobotics/ign-gazebo/blob/model_propshop/src/systems/model_propshop/ModelPropShop.cc#L214-L230)

**Comment by marcoag** [comment]
Moving this to https://github.com/ignitionrobotics/ign-gazebo/pull/1331. I will close the issue.
